<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- produce a classic Program.Main entry point -->
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <!-- turn off the new “implicit usings + top-level statements” -->
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- for Image/Bitmap on Linux you’ll need libgdiplus installed too -->
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
  </ItemGroup>
</Project>
